### ISSUE TITLE
Session recording

### ISSUE THREAD

**Issue by mohithmbansal** [SAP-samples/teched2021-IIS160#2]
Hi, Is session recording available? if yes where can we find it.

**Comment by c-kobo** [comment]
Hi @mohithmbansal, for the limited hands-on session format, there is no recording available. 
Participants can go through the exercises at their own pace based on the description in this repository. 
In the hands-on session, the hosts were just supporting them in case of questions.
The exercise description is detailed enough so that also participants that weren't registered for the hands-on can go trough them. In case of questions, you can raise a new issue here which will be answered by our experts.
